### ISSUE TITLE
媒体匹配为移动端时，底部工具栏被遮挡

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/itonnote-theme#12]
![image](https://github.com/tiddly-gittly/itonnote-theme/assets/32425955/87913707-66a4-4c65-a11d-23f79dc7074b)

**Comment by Zacharia2** [comment]
想问这是独特的设计吗？本意是保留侧边栏，隐藏底部工具栏嘛？

**Comment by Zacharia2** [comment]
https://github.com/tiddly-gittly/TidGi-Desktop/discussions/248

**Comment by dongrentianyu** [comment]
应该是要保留按钮吧。不保留按钮操作起来很不方便的。

**Comment by Zacharia2** [comment]
所以我改成了z-index=200 让他显示

**Comment by linonetwo** [comment]
不大确定，我这移动端能显示，桌面端能正常隐藏
