### ISSUE TITLE
侧边栏不起作用

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/itonnote-theme#15]
![{9ICZN)GGUXTXR@}X8BB9RF](https://github.com/tiddly-gittly/itonnote-theme/assets/109711900/bb3b48ff-7a8e-4453-81cb-63292d88e374)

![)W72A%A1UC4LSY0SXDX7}F2](https://github.com/tiddly-gittly/itonnote-theme/assets/109711900/f3b90d49-43ac-4950-b72b-1542ebc04b9f)

之前都没出现这个问题，我一时也排查不出来是为什么。可能还是插件冲突了，还是样式冲突了。

**Comment by dongrentianyu** [comment]
应该是故事河应该更靠左一点，这相就不会与侧边栏太挤了。但不知道为什么没实现故事河更靠左这一点

**Comment by linonetwo** [comment]
对的，估计是核心优化了一下css，这边得更新一下了，不过我暂时不打算升级 5.3.1 所以我暂时不改这个。5.3.1 暂时去掉了 destroy 方法会导致所见即所得编辑器有bug

**Comment by dongrentianyu** [comment]
那看来新版本的变化还是挺大的。估计可能还会有其他类似的问题，果然要谨慎更新啊，更新前要多备份啊。

**Comment by linonetwo** [comment]
现在应该好了吧，我用着没问题了
