### ISSUE TITLE
桌面端关闭按钮有遮挡

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/itonnote-theme#19]
![截屏2024-02-26 15 36 58](https://github.com/tiddly-gittly/itonnote-theme/assets/3746270/e301e636-c77d-4585-b908-6353ddda2847)

**Comment by linonetwo** [comment]
![图片](https://github.com/tiddly-gittly/itonnote-theme/assets/3746270/6614b3bb-2401-4911-83f7-29e308c6e85f)


![图片](https://github.com/tiddly-gittly/itonnote-theme/assets/3746270/1d87894d-d6bf-44c3-91d8-7be96df1619a)

![图片](https://github.com/tiddly-gittly/itonnote-theme/assets/3746270/b41f3dac-9f01-41c9-b38f-b8733228934d)


在这个插件的网站上无法复现，估计是和别的插件冲突了，你用开发者工具看看 css 是谁提供的吧。

**Comment by dongrentianyu** [comment]
仔细研究了一下才发现是我自己修改了。

在设置-外观-主题调整里，下面有个置顶标题。如果选择了否，就会出现上面的情况。如果选择了是，就不会出现这个问题。
