### ISSUE TITLE
条目下拉列表与条目置顶冲突

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/itonnote-theme#21]
因为itonnote插件的设置，所以itonnote主题默认是置顶条目标题的。但我改成否时，还是会置顶标题。

![image](https://github.com/tiddly-gittly/itonnote-theme/assets/109711900/5f5f478d-1a08-45e5-92f7-de416a464146)

效果如图。相当于这个修改没有生效。后面我找了发现是`$:/themes/linonetwo/itonnote/base`代码里写了相应的设置。

我在网站尝试修改后，发现是从第56行开始设置的。

```
div.tc-tiddler-title {
  background: <<colour tiddler-title-background>>;
}
/** 编辑器工具栏 position: sticky; z-index: 890; backdrop-filter: blur(10px);*/
``` 

这里应该是需要把position和z-index以及backdrop-filter，都注释掉，才能正常使取消条目置顶效果生效。

我之前好像在另一个仓库里提到这个问题了。但想不起来了。

如果需要提pr的话，可以告诉我。

**Comment by dongrentianyu** [comment]
提交pr了。

**Comment by dongrentianyu** [comment]
可能直接删除会更好，但谨慎起见，还是保留着。习惯性把不需要的代码注释起来，以免后面需要用。

**Comment by linonetwo** [comment]
应该在主题里把条目标题的 z-index 改大一点
